ajayyy/SponsorBlock

background.js, content.js, manifest.json, popup.html, popup.js, utils.js
This is my version of the Utils
There is also https://github.com/ajayyy/SponsorBlock/pull/85
=> Added Utils file + Updated Parser

background.js, content.js, manifest.json, popup.js
Removing use of tab.url as its not needed
Status: Awaiting Review
=> Removed tabs permission

manifest.json
https://github.com/ajayyy/SponsorBlock/issues/82
=> Added youtube-nocookie.com

content.js
=> Fancy tooltip for player controls

_locales/en/messages.json, _locales/pt_BR/messages.json, _locales/pt_pt/messages.json
- Add european portuguese translation
- Improve brazillian portuguese translation
=> Add european portuguese translation

content.js, manifest.json
Thanks to https://github.com/ajayyy/SponsorBlock/pull/163#pullrequestreview-313515325
=> Fixed notice never hiding

_locales/fr/messages.json
A few fixes, improvements and missing translations to the french localization strings.
=> Improve French translation

_locales/en/messages.json, background.js, content.js, manifest.json, popup.js
This should help Firefox users moving to new computers. Firefox storage sync is slow.
=> Fixed error message, prevented double counting contributions and delayed userID generation

_locales/en/messages.json, _locales/pl_PL/messages.json, help/index_en.html, help/styles.css, options/options.css, options/options.html
- Fix css when using html5
- Add encoding scheme to html
- Remove font-size change on title on hover. It's jarring
seeing the whole page move when trying to move your mouse
to the options.
- Remove center tags
- Remove unnecessary styles
- Fix some minor grammar
=> Set options and help page to use html5

manifest/manifest.json, src/config.ts
Resolves https://github.com/ajayyy/SponsorBlock/issues/268
=> Fixed Firefox recursion issue

manifest/manifest.json, src/content.ts, src/js-components/previewBar.ts, src/js-components/skipNotice.ts, src/popup.ts
Support for https://m.youtube.com
=> Mobile YouTube support + Precise skipping

src/popup.ts
The pop now says "So far, you've submitted 0 sponsor**s**" instead of "So far, you've submitted 0 sponsor".
=> Fix "0 sponsor" in popup

.github/workflows/release.yml, manifest/manifest.json, src/content.ts, src/js-components/skipNotice.ts
The last version broke non zero second skips.
Fixes auto skip scheduling.
Prevents manual skip auto-votes from affecting the UI.
Prevents manual skip auto-votes if disabled.
=> Fix non zero second skips

public/_locales/en/messages.json, public/options/options.html, src/config.ts, src/options.ts
Provides an object which can be added to bug reports to help the developer find issues which could be due to config/platform issues.
Reasons to use over the config output:
- Output is sanitised to protect user data.
- Provides platform information
- Provides extension version
Example output for chrome/firefox:
Firefox: 
```
{
"debug": {
"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0",
"platform": "MacIntel",
"language": "en-GB",
"extensionVersion": "1.2.22"
},
"config": {
"hideDiscordLaunches": 1,
"sponsorTimes": {
"id": "sponsorTimes"
},
"whitelistedChannels": 0,
"startSponsorKeybind": ";",
"submitKeybind": "'",
"minutesSaved": 0,
"skipCount": 0,
"sponsorTimesContributed": 0,
"disableSkipping": false,
"disableAutoSkip": false, …
```
=> Added copy debug information to clipboard options element.

README.md
=> Fix typo in Chrome Users badge

public/_locales/en/messages.json, public/options/options.html, src/config.ts, src/content.ts, src/utils.ts
Config.config.timeWithSkips
Config.config.hideRealTime
=> Added config option for excluding skipped content from the video duration

public/_locales/en/messages.json, src/components/SponsorTimeEditComponent.tsx
Add a review button to the submission edit popup #393
=> Add review button to submission popup

public/_locales/de/messages.json
fixes missing bracket on line 315
=> German translation hotfix

src/content.ts, src/popup.ts
While 0253016, 06d600c and fd8a3a0 removed a bunch of unused code, there are still a few functions and remote calls that are unused.
These changes come from 8c6b0ad which was made mostly obsolete by the previously mentioned commits.
=> Remove unused popup related code

src/content.ts
=> Potential fix for video replaying after browser stutters on Firefox.

src/content.ts
Fixes https://github.com/igrigorik/videospeed/issues/683 and https://github.com/ajayyy/SponsorBlock/issues/359
Requires https://github.com/igrigorik/videospeed/pull/740
=> Listen to custom videospeed event

.eslintrc.js, src/background.ts, src/components/CategoryChooserComponent.tsx, src/components/CategorySkipOptionsComponent.tsx, src/components/NoticeComponent.tsx, src/components/NoticeTextSectionComponent.tsx, src/components/SkipNoticeComponent.tsx, src/config.ts, src/content.ts, src/globals.d.ts, src/js-components/previewBar.ts, src/options.ts, src/popup.ts, src/types.ts, src/utils.ts
=> Fix eslint warnings

src/content.ts
=> Ensure correct start- endtime order

.eslintrc.js, src/components/SkipNoticeComponent.tsx, src/utils.ts
This should mark the end of the refactor efforts related to eslint! :tada:
=> Replace self-equals-this code with arrow functions

public/icons/clipboard.svg, public/popup.css, src/popup.ts
this PR adds a button to copy the segment uuid to the popup. i don't know if i like that copying the uuid gives no response, but i guess it's unnecessary.
=> add uuid copy button to the popup

src/popup.ts
Closes #678 
Also fixed small typo
=> fix wrong saved time rounding

README.md
The README's license section has not been updated after the change to the LGPL. This PR fixes that.
***
=> Update README after license change

public/content.css, public/help/styles.css, public/options/options.css, public/permissions/styles.css, public/popup.css, public/popup.html, src/content.ts
=> Make dark scroll bar in Chromium-based browsers

src/components/SponsorTimeEditComponent.tsx
***
closes #874 by reducing the precision of inspect segment
=> reduce precision of previewTime

src/components/SubmissionNoticeComponent.tsx
=> Fix typo in SubmissionNoticeComponent

public/popup.css
=> Fix username wrapping

src/components/SponsorTimeEditComponent.tsx
=> Preview skip-lenth dependant on playbackspeed

src/components/SponsorTimeEditComponent.tsx, src/content.ts
=> unsubmitted segments are initialized rounded to 3 digits

package.json
=> Update licence in package.json

src/popup.ts
=> Changed comments from seconds and hours to minutes

public/_locales/en/messages.json, src/popup.ts
=> Format minutes now Days, Hours and Minutes

src/components/SkipNoticeComponent.tsx, src/content.ts
Moves audio notification to content.ts
Fixes  #756
***
=> Decouple audio notification from Skip Notice

src/utils.ts
***
Hey I noticed that over several hours of use the CPU usage of youtube music would get worse and worse. After a quick check I found that the set interval here is piling up if the condition never becomes true. I was having hundreds of setIntervals firing every second.
=> fix leak that was killing performance over long periods

src/popup.ts
***
Fixed the conversion of minutes to days from 3600 (seconds to hours) to 1440 (minutes to days)
=> Fixed minute to day conversion

src/content.ts, src/utils.ts, src/utils/pageUtils.ts
***
Excluded
- Info/ Delete/ Upload button
What works/ doesn't
closes #58
=> Detect segments on channel trailers

public/options/options.html, src/content.ts, src/utils.ts
- I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
=> Add missing localizations

.github/workflows/updateInvidous.yml, ci/invidiousCI.ts, package-lock.json, package.json
- add ts-node
- fix path
- add npm ci
***
This can be manually invoked since it missed the last 2 automated runs, there **are** instance changes
=> fix updateInvidious ci

src/content.ts
=> early return if url is youtube clips url

.github/workflows/update-oss-attribution.yml
***
couldn't test properly on another branch but should work in theory
=> Fix OSS CI

src/content.ts
=> Improve precision of skips on both chromium and firefox

src/content.ts
- I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
***
Certain actions like alt+tabbing were able to break keybinds.
=> Fix keybind sometimes not working

src/utils/genericUtils.ts
closes #1221 - CloudFlare errors are now bearable
=> custom error handler for 5xx

src/popup.ts
=> Get user infos from userInfo api for popup

src/utils/genericUtils.ts
#1222
#1221 
relevant message in private channel
https://discord.com/channels/603643120093233162/737501773358694431/952060191262781501
=> ignore body if cloudflare error found

src/components/SubmissionNoticeComponent.tsx
=> Fix guidelines link

public/content.css, src/content.ts
***
small fixes & rearranged code
=> Misc fixes

public/_locales/en/messages.json, public/popup.css, public/popup.html, src/popup.ts
=> Add beta server warning to popup

.eslintrc.js, package-lock.json, package.json, webpack/webpack.common.js
***
- update dependences
- don't update react b/c of breaking changes
- downgrade webpack to reduce one security risk
- change over to `fork-ts-checker-webpack-plugin` to reduce build times by 1/3
=> bump dependencies

src/config.ts, src/content.ts, src/popup.ts
=> reuse userinfo for isVip and remove lastIsVipUpdate

src/config.ts
=> remove lastIsVipUpdate from config

public/content.css, src/content.ts, src/js-components/previewBar.ts
=> add selector for mobile YT chapters

src/background.ts, src/config.ts, src/content.ts
***
Fixes #1328.
Tested this change on Chrome 102 and Firefox (I do not own any Apple device).
=> Use Navigation API when available

public/popup.html, src/background.ts, src/content.ts, src/help.ts, src/messageTypes.ts, src/options.ts, src/permissions.ts, src/popup.ts, src/utils.ts, src/utils/pageUtils.ts
- [🦆 ] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
***
=> Move popup to iframe and restrict embeds

src/popup.ts
***
closes https://github.com/ajayyy/SponsorBlock/issues/1353
=> display "Voted!" message only momentarily

package-lock.json
=> Fix npm ci failing

.github/workflows/tests.yml, test/selenium.test.ts
Replaces #868
Doing the next step of running a local server would still be very useful though, or using a test server domain
=> Run Selenium tests in GitHub actions

src/content.ts, src/messageTypes.ts, src/popup.ts
show connectionError string if status is not 404
closes #1364
***
=> Show connectionError string if status is not 404

README.md
=> Fix the readme for SponsorLock

src/options.ts
=> append timestamp to export filename

public/content.css, src/components/SponsorTimeEditComponent.tsx
***
This PR aims to fix theming issues with Dark Reader and Invidious, where text in the submit popup is impossible to read.
Tested on Firefox & Brave, on Youtube and Invidious, with light & dark themes, with and without the dark reader extension.
fixes #952
=> Fix issues with DR & Invidious themes

src/popup.ts
=> allow disabling mute segments locally

src/utils/genericUtils.ts
=> catch all html in error messages

manifest/manifest.json, src/content.ts, src/document.ts, src/types.ts, webpack/webpack.common.js
=> rebase document script out of videoInfo

public/_locales/en/messages.json
***
- also changes capitalization of UserID to be consistent across all strings
=> update UserID to be Private UserID

src/popup.ts
=> popup votebuttons disappear fix

src/content.ts
***
ramblings and dissections in [discord](https://discord.com/channels/603643120093233162/1021293986964582470)
without wrapping it, it tends to have much larger overflows, creating a very distracting effect when using the arrow keys to skip back and forth
=> wrap popup in #secondary-inner

public/content.css
***
- fixed regression from #1427 that cause lock highlights to be hidden
=> fix VIP LockCategories

src/popup.ts
=> don't append skip button for full video labels

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/update-oss-attribution.yml, .github/workflows/updateInvidous.yml
=> bump actions to node 16

src/content.ts
***
closes #1525 
doesn't seem to bind on first load but that's part of another error (will open issue)
=> add YT Music progress bar selector

src/components/SponsorTimeEditComponent.tsx
=> Don't overwrite endcards time upon submitting

public/_locales/en/messages.json, public/options/options.html, src/components/SponsorTimeEditComponent.tsx, src/config.ts
***
Fixes https://github.com/ajayyy/SponsorBlock/issues/1576
=> Add option to disable scrolling to edit

src/content.ts
=> Don't include mutes in time without skips

src/content.ts
***
PR is easier than rebasing #1424 
Closes #1414
=> only allow full video labels on livestreams

src/content.ts
***
as detailed in https://github.com/ajayyy/SponsorBlockServer/pull/412, partial hashes are possible but aren't correctly highlighted on the seekbar since the check is strict
=> highlight partial required segments

src/utils.ts
***
fixes [giant](https://imgur.com/wmTJ0i9) export button on third party sites by loading shared.css
=> load shared.css on third party sites

webpack/webpack.common.js
start of complaining: https://discord.com/channels/603643120093233162/603643256714297374/1088914848483647568
start of more complaining: https://discord.com/channels/603643120093233162/607338052221665320/1088926848265764906
solution: https://discord.com/channels/603643120093233162/607338052221665320/1088939637495562240
=> fix paths for windows dev

public/_locales/en/messages.json, src/content.ts
=> Spelling fix

src/content.ts
***
Almost no code changes were required to do this. Only difference between youtube and invidious is that we don't want to add any classes to the attached span element.
closes #1717
=> Show time with skips removed on invidious

public/_locales/en/messages.json, src/components/NoticeComponent.tsx
- [ x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
***
=> Add notice time to translation file

src/content.ts
=> Add border radius like other YouTube elements

README.md
I did not manage to clone the submodule with the given command, this one worked.
=> Update the git clone with submodule command in README

CONTRIBUTING.md
not even the first time us windows users have been oppressed by big linux 😔
=> update CONTRIBUTING for windows

ci/invidiousCI.ts, ci/invidiousType.ts, ci/invidiouslist.json, public/options/options.html, src/content.ts, src/js-components/previewBar.ts, src/utils.ts
closes #1720 
dependent on https://github.com/ajayyy/maze-utils/pull/8
closes https://github.com/ajayyy/SponsorBlock/pull/1792
=> Add support for YT Kids

CONTRIBUTING.md, README.md
- reformatted windows build issues
- updated contributing to reflect LGPL-3.0-or-later
- replaced Invidio.us with Invidious
- replaced API docs link
- updated Invidious API link
=> [docs] move building from readme, formatting tweaks

CONTRIBUTING.md
=> add translations to contributing

src/popup.ts
***
I know this won't effect 99.9% of people using the extension but is a nice to have for the 0.1% that is.
Please also check ExtensionTranslations [PR #33](https://github.com/ajayyy/ExtensionTranslations/pull/33)
=> Added years to time saved display

README.md
Hi! 
I think you may forget to update the license to GPL in README.md
=> Fix license info in README

src/config.ts
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
=> Fix comment typo

manifest/chrome-manifest-extra.json, manifest/firefox-manifest-extra.json, manifest/manifest-v2-extra.json, manifest/manifest.json, manifest/safari-manifest-extra.json, src/background.ts, src/content.ts, src/globals.d.ts, src/utils.ts, src/utils/logger.ts, webpack/webpack.manifest.js
=> Support mv3

ci/generateList.ts, ci/invidiousCI.ts, ci/invidiousType.ts
=> fully typed updown response

src/content.ts, src/utils/segmentData.ts
***
depends on ajayyy/maze-utils#14
=> Use useragent generator from maze-utils

src/background.ts, src/components/CategoryPillComponent.tsx, src/components/ChapterVoteComponent.tsx, src/components/SponsorTimeEditComponent.tsx, src/content.ts, src/dearrowPromotion.ts, src/messageTypes.ts, src/options.ts, src/popup/PopupComponent.tsx, src/popup/SegmentListComponent.tsx, src/popup/YourWorkComponent.tsx, src/utils.ts, src/utils/requests.ts, src/utils/segmentData.ts, src/utils/videoLabels.ts, src/utils/warnings.ts
***
- pass errors from background threads back to clients
- log all HTTP request errors and display them to the user where possible
Depends on: ajayyy/ExtensionTranslations#97, ajayyy/maze-utils#15
<details>
<summary>Screenshots</summary>
</details>
=> Improve error handling

src/popup/SegmentListComponent.tsx
***
Friendship ended with recursion, chapter stack is my new friend
side effect: fixes popup crash for videos where the first segment is not a chapter
[debugging thread on discord](https://discord.com/channels/603643120093233162/603643256714297374/1419050893965394023)
=> Rewrite chapter nesting code
