ajayyy/SponsorBlock

manifest.json

Remove files in help/ directory from web_accessible_resources in manifest.json because the help page opens in context of the extension (no need to expose it to other contexts).

Remove help/* from web_accessible_resources

---

_locales/fr/messages.json

Native speaker here, the machine based translation was not great so here's a first draft.
I choose to use "_message commercial_" (commercial message) and not "_publicité_" (advertisement) since ads feels to me to be more a legal status than a definite thing. "Endossement" is not a valid french word in this context, and endorsements would be translated to "_sponsors_" or "_mécénat_" in fr_FR, but again this are more legal category than pure identifying terms and fr_CA strongly dislikes frenglish.
But I left it in the extension name since this is a good keyword for people looking for adblocking-related extensions.

Better french translation

---

content.js

The only value that appears to be used from the API response is `published`.  in which case it's possible to use `/api/v1/videos/ID?fields=published` ([docs](https://github.com/omarroth/invidious/wiki/API#fields)), which cuts down the size of the response by about 99.9% for most videos.

Only request published field from Invidious API

---

.gitignore
background.js
firefox_manifest-extra.json
manifest.json

This stops Firefox from throwing an error every time user changes tabs if the addon is installed at all. It also moves the browser specific settings into the main manifest file which only causes Chrome to throw a warning when loading the unpacked extension and with no changes when installing the .crx.

Some Firefox Optimizations

---

.github/workflows/ci.yml
.gitignore
README.md
package-lock.json
package.json

This adds a CI using GitHub Actions to generate build artifacts of the extension.
This generates artifacts for both Chrome and Firefox.
This uses `web-ext` to generate the artifacts. web-ext is also handy for running the extension under a clean Firefox profile. However, if the project doesn't want to add web-ext, and instead do something more custom, like running a script that just zips everything relevant, then that is fine, I can look into that.
See https://github.com/jplsek/SponsorBlock/runs/367214841 (top right is the artifacts button)
I'm not exactly sure what other files should not be included in the zip. Let me know (or make a commit). (see the `-i` argument in the package.json build script)

Add web-ext and ci artifact generation

---

public/_locales/en/messages.json
public/options/options.css
public/options/options.html
src/config.ts
src/options.ts
src/utils.ts

Let the user set a config value to use a different server without a custom build of the extention.
I maintained the ability to use the existing config.json approach to not break existing dev workflow - if you don't want this let me know and I'll change it to use the default config.

Add custom server address

---

src/popup.ts

If we parse seconds as Int we loose possible decimals which makes it impossible to fine tune sponsor times when using the edit function

Retain decimals in seconds value when editing sponsor times

---

public/_locales/en/messages.json
src/options.ts

Setting certain keys as keybindings can cause it to interfere with keybindings youtube uses.
This restricts the user from setting those keys as keybindings, as well as any other keybinding the user has set SponsorBlock to listen for.
The method of alerting the user may need to be changed.
List of keys youtube uses taken from here:
https://www.hongkiat.com/blog/useful-youtube-keyboard-shortcuts-to-know/

Restrict keybindings

---

src/content.ts

Videos that start with a sponsor skip ads that occur before the video starts. This PR disables skipping when an ad (not banner ad) is playing and also hides the green sponsor preview bar and sponsor submission controls.
Example of video that always seems to start with a full player ad:
[https://www.youtube.com/watch?v=YuRYaTVSuhs](https://www.youtube.com/watch?v=YuRYaTVSuhs)
You can use that for verifying this works, if the ad at the start doesn't show, clearing cookies should make the ad show

Don't skip ads, hide controls & sponsor times preview bar when ads are playing

---

public/_locales/en/messages.json
public/popup.html
src/content.ts
src/popup.ts

Some of the "to" between timecodes haven't been localized, and "Close Popup" was hard-coded in, as well as the "Sponsor Editing has been moved..." message.

Missing localized messages

---

package-lock.json
package.json
public/_locales/en/messages.json
public/options/options.html
src/config.ts
src/content.ts
src/utils.ts

This feature changes the way segments are obtained from the server in a way that improves user privacy, but disables fetching sgements while the video is being played should they be submitted. 
Instead of requesting segments using the video ID (the string after watch?v=), the video ID is hashed and the first 4 characters of the hash are sent to the server, which returns all videos where the hash also starts with those characters. The client then selects the video it wants (if any) and uses the segments provided in that request.

Added hash prefix implementation (server code not yet merged) 

---

public/_locales/fr/messages.json

Changing timer to minuteur : it's an anglicisme, not a french word, same for liker and follow
Changing "segment non-musicale" to "segment non-musical" because segment is a masculine word
And fixing a typo at line 499

Fixing typo and removing 'anglisismes'

---

public/_locales/de/messages.json

- [German has pronouns for both familiar/informal and polite/formal forms of address](https://en.wikipedia.org/wiki/German_honorifics). Half of the strings were formulated polite/formal, while the other half was not. Using the polite/formal forms is a little bit overkill for this use case. I've changed all sentences to use the familiar/informal forms.
- former translation was poor, made no sense, was too hard to understand or didn't contain the actual meaning
- affected lines: 77, 137, 149, 158, 203, 290, 347, 425, 428, 489, 516, 522, 528, 543, 547, 599
- general improvements like small fixes, better grammar, easier to read sentences
- applies to all edited lines, including the lines already mentioned above

Major improvement for German translation

---

src/content.ts

This should fix #426 
**The problem:**
If SponsorBlock skips to the end of a video in a playlist which is set to loop, the looping doesn't work, instead it goes to the next video in the playlist.
**Solution:**
Check if the time to skip to is at the end of the video, if it is and the video is set to loop, jump to the beginning.

Fix: skipping to the end of looped videos #426

---

public/_locales/de/messages.json
public/_locales/el/messages.json
public/_locales/en/messages.json
public/_locales/es/messages.json
public/_locales/fi/messages.json
public/_locales/fr/messages.json
public/_locales/id/messages.json
public/_locales/it/messages.json
public/_locales/ja/messages.json
public/_locales/ko/messages.json
public/_locales/nl/messages.json
public/_locales/pl/messages.json
public/_locales/pl_PL/messages.json
public/_locales/pt_BR/messages.json
public/_locales/ro/messages.json
public/_locales/ru/messages.json
public/_locales/sk/messages.json
public/_locales/sv/messages.json
public/_locales/tr/messages.json
public/_locales/uk/messages.json
public/_locales/vi/messages.json
public/_locales/zh_CN/messages.json
public/_locales/zh_TW/messages.json
src/components/SkipNoticeComponent.tsx

Hi there! This is my attempt to resolve #447.
> "Überspringen Unterbrechung?" should be "Unterbrechung überspringen?" but on crowdin I could only find these strings as separate parts so the grammar cannot be fixed in the translation. You would need to update the translation template to include all whole strings and not piece together the translation as it is doing now.
I updated the default locale translation template with new strings, translated them into German and updated the skip notification popup code to use them. I hope that this is the way to go - I didn't work with crowdin yet 😬.
An alternative solution may add locale specific code [here](https://github.com/ajayyy/SponsorBlock/blob/56136d598bc1c960bc50ab09bf21ead903010370/src/components/SkipNoticeComponent.tsx#L80):
```js
if …
```

fix: resolve translation template issue

---

src/content.ts

**Problem**
Sometimes segments at the start of a video are not skipped. For me, it happens if I restart my Firefox, go to YouTube, and click a video which has segments at the start.
**Video**
I made a video to show the problem.
https://youtu.be/xwyLslTYSmw
In the first half you can clearly see, that the segment doesn't skip, because I just restarted Firefox. After that, I restart Firefox again and load my modified version, which fixes this.
**Reason**
In `sponsorsLookup(id)`, the `video` variable may be `null` (maybe because of slow internet/slow hardware). This results in a retry-loop with 100ms delay. The video likely already started playing now, but the event listener for the `play` event of the video is not yet added. Because of that, `switchingVideos` is never set to `false`, and …

Fix: segment at the start not skipping

---

public/content.css
src/components/SponsorTimeEditComponent.tsx
src/utils.ts

Changes the segment editor to use a single input field for both the minutes and seconds part of the segment boundary times.
Additionally, removes unused util functions and saves the edits on changes to allow users to preview their changes immediately on the progress bar and to allow previewing by manually clicking on the progress bar without accidentally using the old values.
If either of the fields contains an invalid input, the time change is ignored entirely.
The input field is rather permissive, allowing for quick inputs:
- The already used time format is supported (`1:20:34.12` = 1h20m34s120ms)
- An empty field is interpreted as "start of the video" (0s)
- Input containing just a number is interpreted as seconds (`24` = 24s, `15.3` = 15s300ms)
- Input containing just a number …

Use formatted time inputs for segment editing

---

public/_locales/de/messages.json

This PR fixes two problems in the German translation of the `supportInvidiousDescription` string.
The rest of the file uses non-honorific pronouns, so this line should also use them (i.e. "du" instead of "Sie"). See also [my comment in PR #632](https://github.com/ajayyy/SponsorBlock/pull/632#pullrequestreview-582290744).
Plus: There is a typo in the word "Incongnito" (an extra "N"), and it is linked to the word "Modus" which should be uppercase when linked with a hyphen. But even if none of those typos were there it would *still* be incorrect, because Chrome uses the spelling "Inkognitomodus" (which is what I changed it to in this PR).

Fix German pronouns and typo

---

src/content.ts
src/utils.ts

getFormattedTime() with nothing passed into it and a couple other edge cases returns (NaN:NaN). This is a problem since on a slow machine getFormattedTime gets called without anything passed into it around the same time the computer is fetching the sponsor data. I haven't found the exact time/cause/scenario that it is causing it to return  this, but this function at some point returns (NaN:NaN), and this will definitely fix it. I've have a slow machine so it's really been bugging me seeing (NaN:NaN) in the video bar for a couple seconds before the page fully loads. Hopefully this should fix it.
P.S. If you want some other case during the loading (e.g. nothing instead of "0:00") that would work as well.

Fixed getFormattedTime sometimes returning (NaN:NaN)

---

public/popup.css

The options icon before was not vertically centered. This only appeared in firefox.

Fix options button icon in firefox

---

src/content.ts

The root div of the player is not `#player-container` in invidious embeds but just `#player`. The `addHotkeyListener` function failing seems to be the root cause of all sponsor blocking failing on invidious embeds.
Fixes #645

Fix the videoRoot to also work on invidious embeds

---

src/content.ts

This partially resolves issue #213 by using a different selector in addHotkeyListener() when viewing YouTube's TV interface at youtube.com/tv. Before this fix addHotkeyListener() would return an exception and lead SponsorBlock to assume that there are no segments in the video.
I couldn't get the SponsorBlock buttons and progress bar to work unfortunately, as YouTube TV's interface is completely different from standard YouTube.

Partially fix YouTube TV support

---

.gitignore
public/help/index_en.html
src/content.ts

Closes #743 
```typescript
// value determining when to count segment as skipped and send telemetry to server (percent based)
let manualSkipPercentCount = 0.5;
```
This variable controls when manual skip is considered "fullSkip". If it is considered full skip telemetry will be sent to the server. If not it will be only counted locally. Also, when segment was skipped is current "watch session"(resets after window reload) skip will not count and telemetry will not send.
Added here commit with help updates that closes #732

Skip count sending and counting on manual skip

---

public/_locales/en/messages.json

Change "Set key for start segment keybind" to "Set key for start/stop segment keybind", since it is more accurate to the actual feature!

Change to "start/stop segment keybind"

---

README.md

Since the README still contained the [old link to 3rd-party-ports in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Unofficial-Ports), I edited it to be [the new one](https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports)!

edit old link to 3rd-party-ports in README.md

---

src/components/SponsorTimeEditComponent.tsx

***
If you choose any category when editing a segment, and then choose the "Choose a category" one, it triggers the enable category message with an empty category name. This is a fix for that.
Tested, works.

Fix for an "enable category" popup

---

src/components/SponsorTimeEditComponent.tsx
src/render/RectangleTooltip.tsx

Makes rectangleTooltip fontSize bigger

---

README.md

Included links to relevant browser documentation, added an explanation for the mysterious `CompileConfig` errors, and made the command to build the development version the more prominent variant (as it's arguably more useful in development).
Preview [here](https://github.com/opl-/SponsorBlock/tree/docs/readme-building#building).

Add more detail to building section of readme

---

src/utils/noticeUtils.ts

***
fixes error 
```ts
Uncaught TypeError: Cannot read properties of null (reading '0')
at Object.t.downvoteButtonColor
```

fix "cannot read properties of null" when voting on full video tag

---

src/content.ts

- I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
***
The focus event was not firing in Chrome on document, only on window.
Fixes keyboard shortcuts messing up after alt+tab in Chrome. (from #1197)

Fix alt-tab, round 2

---

public/options/options.css

- I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0
***
Fixed double scrollbar:
Centered options in <800px windows. It suddenly jumping to the left was jarring. Also removed huge whitespace on this small window size, because I think every bit of space matters here. Feel free to disagree of course :)

Settings css fixes

---

src/content.ts

***
This disables the `switchingVideos` check in the `startSkipScheduleCheckingForStartSponsors` function for Safari as discussed in #1142.
Closes #1142

fix: ignore switchingVideos in Safari

---

public/popup.css
public/popup.html

New user here - great service! Only area I was slightly confused by was the "popup" that appears when you click the extension icon. I found it wasn't immediately clear what the main actions were.
uBlock Origin for example has clear [menu bars](https://i.imgur.com/Yr9LoFM.png) that I think might help improve the structure of this area.
This PR refactors the "popup" HTML and CSS to introduce a basic menu bar for the main actions.
I believe this PR to be production-ready, but it's only a "first pass" at improving this area of the extension. If this gets merged and you like the direction this is heading I'm happy to follow it with some more areas of improvement I see.
**On YouTube page:**
**Not on YouTube …

Add menu bar to popup

---

public/popup.css
src/popup.ts

- It's not very clear that segments can be expanded/collapsed. A hover state would help indicate each segment can "do something" when clicked.
- The expand/collapse of these time segments is done via JS, which is unnecessary considering the [`<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). It also has subtle issues like being unable to collapse after voting.
- Add hover state to time segments
- Replace JS expand/collapse with `<details>` element
Also:
- Remove unused `.popupElement` class
***

Refactor segment expanding to use <details>

---

public/popup.css
src/content.ts
src/popup.ts

- The popup width doesn't match the YouTube sidebar width when displayed in-page.
- The "Close Popup" link is very small and easily missed. I would expect a close icon top right, similar to what is mentioned in #594.
- The "You've saved" and "You've skipped" paragraphs aren't on their own line (small regression in #1189) ([screenshot](https://i.imgur.com/VqeXMmS.png)).
- Allow width of popup to fill container when displayed in-page.
- Move the "Close Popup" button to the top right of the popup as an icon.
- Use `display: block` instead of `display: unset` for showing "You've saved" and "You've skipped" paragraphs.
To test this pull request, follow the [instructions in the …

Fix popup width and improve close button

---

README.md

There seems to be a difference in how you need to load `/dist` contents in to Firefox vs Chrome i.e. in Chrome you can load the "unpacked" folder itself, in Firefox you need to load a ZIP.
I bumped in to this when following the instructions, so this updates those instructions to clarify the difference.
***

Improve "load in Firefox" docs

---

src/content.ts

Closes #1249. @mchangrh 
This PR:
- Fixes desktop YouTube channel ID lookup. Previously it would grab entries from the Home tab which could sometimes be open in the background, and this also caused channel custom URLs to sometimes be grabbed as well.
- Potentially makes the Invidious lookup more stable.
- Makes the Regex more strict and reliable.
The reason the Invidious lookup uses `.channel-profile #channel-name` instead of just `#channel-name` is because the YouTube desktop client also uses `#channel-name`, but has over 50 instances of it. The `.channel-profile` makes sure the Invidious selector cannot accidentally match the wrong element in the YouTube desktop client. (if for example the chained selectors were converted to a promise race in the future)
***

Improve the channel ID lookup.

---

src/components/SponsorTimeEditComponent.tsx

This PR makes the `Preview` button in the segment editing component start video playback at the segment's end if the segment starts exactly at `0:00`.
This basically fixes a minor annoyance that I (and possibly others) had when trying to fine-tune a segment starting at `0:00` - the first frame of the video flashing for a "second".
~~Also WebStorm decided to remove a bunch of whitespace from the file, I hope that doesn't cause too many issues. The main code edits start at line 535.~~ Changes undone
I've tested this pull request and it seems to be working as intended.
***

Start playback of edited segment at it's end when it starts 0:00

---

public/popup.css
public/popup.html
src/popup.ts

- The "consider enabling force channel check" alert has wrapping text and pushes the content down quite a lot
- The alert doesn't disappear when the thing that triggered it is toggled off
- Couple minor spacing regressions in #1189
- Forced popup width causes horizontal scrollbar/misalignment in Firefox
- Lack of `max-height` can cause Firefox popup to be too large/cause scroll issues
- Use colours instead of font size/weight to make the alert noticeable
- Hide the alert when "Remove channel from whitelist" is clicked
- Fix some spacing regressions
- Add `max-width: 100%` to fix Firefox popup width issues
- Add `max-height: 600px` (only in popup context) to fix Firefox popup height issues
This also tidies/simplifies the popup CSS a bit. …

Improve popup alert and fix Firefox issues

---

public/content.css
public/popup.css

If you hover over a segment's voting buttons when the popup is rendered in-page, they slightly reduce in opacity.
But if you hover over the voting buttons when the popup is rendered in the dropdown, they do not change in opacity.
This difference in behaviour based on where the popup is rendered looks like a bug to me.
Fix this by removing `.voteButton` CSS from `content.css` and adding the missing `.voteButton:hover` CSS to `popup.css`
Also:
- Prefer `opacity` over `filter` for changing opacity
***

Fix vote button hover inconsistency

---

public/_locales/en/messages.json

Fixed the following in [`public/_locales/en/messages.json`](https://github.com/ajayyy/SponsorBlock/pull/1220/commits/a64deb2e1811129d4f812d02651bde282e041735#diff-d5a5a9eb2f0d2c86006fb09bf07a55d4af6227b1dba33edb6c36a78871f1641f):
- Typo "occured" -> "occurred"
- Changed two instances of "seekbar" and "Seekbar" to the already used "Seek Bar"
- Changed one instance of "autoskip" to the already used "auto skip"

Fix minor typos and inconsistencies

---

src/content.ts

- add awaiter for key element
- refresh ID with segments if videoID is invalid
closes #1386 
***

fix embeds not being detected correctly

---

public/_locales/en/messages.json

***
after some discussion in the discord, it was revealed that the description in the extension did not match what the current guidelines were for previews

update wording of Preview to be inline with wiki

---

public/popup.css
src/popup.ts

Looks like the "popup embedded in the YouTube sidebar" was moved to an `<iframe>` in #1322.
This broke a CSS selector which was there to remove the fixed `width` from the popup when it's embedded in the page:
https://github.com/ajayyy/SponsorBlock/blob/780ea4a9d0b12762d10e787786816e3e8a6f9b26/public/popup.css#L113-L115
_(this was added in #1228)_
Because this selector no longer works, when the popup is rendered in the YouTube sidebar it does not fill the full width.
Add `.is-embedded` class to the `<body id="sponsorBlockPopupBody">` element when it is rendered in the page.
This is then used in the CSS to replace the broken selector.
To test this pull request, follow the [instructions in the …

Fix popup width when embedded in page

---

public/_locales/en/messages.json
public/popup.css

Ever since using this (excellent) extension the labelling of the main "Segment Starts Now" button has irked me 🙂 
Button labels should typically start with a verb i.e. the "action" that will be performed - "Start" in this case. Right now in both "states" of the button, the label starts with a noun - "Segment" in this case.
User shouldn't need to read somewhere in the middle of the button to determine the "state" the button is in.
- `Segment Starts Now` -> `Start Segment Now`
- `Segment Ends Now` -> `End Segment Now`

Improve copy of start/end segment button

---

src/content.ts

***
This was reported a few times on discord. Seems like the X (cancel creating segment) button on the controls panel didn't delete the entry when it was empty. The Delete button in the submit notice did have that logic though.

Remove the unsubmittedSegments entry when removing the last segment

---

src/background.ts
src/content.ts
src/messageTypes.ts
src/popup.ts

***
This PR:
* Triggers a segment list refresh in the popup when content script loads new ones
* Changes the return value of `getYouTubeVideoID` on fail to `null` (simplifies type annotations & logic)
* Deduplicates and cleans up popup -> content script communication code in `popup.ts`
* Removes the `sendMessage` function
* Modifies `sendTabMessage` to use a provided callback, adds `sendTabMessageAsync` that returns a promise
* Modifies any function that duplicated `sendTabMessage` code to call `sendTabMessage` or `sendTabMessageAsync`, making them async if needed and adding type annotations for response objects

Update popup on segment updates + some code cleanup

---

src/options.ts
src/popup.ts
src/utils/licenseKey.ts
src/utils/warnings.ts

***
This should reduce the load on the server a bit, as it will no longer have to compute the publicID for each sponsorblock user. 
This also reduces the list of actions that leak the privateID to the server.

Use publicID instead of privateID for /userInfo calls

---

src/popup.ts

***
Update segment element classes instead.
This probably is more efficient than what we're doing currently. Also, this seems to fix a bug where the vote confirmation/error msg is removed immediately

Don't update the whole segment list on time update

---

webpack/configDiffPlugin.js
webpack/webpack.common.js

add config diff plugin to throw a warning if `config.json` differs from `config.json.example`
This is helpful if there's an change/update to the category list

config diff plugin

---

manifest/manifest.json
src/content.ts
src/utils.ts
src/utils/pageUtils.ts

closes #1243
- add playerInit listener for piped
- add piped specific selectors
- explicitly add css files to web accessible resources
Working
- Preview bar segments
- videoID detection
- skipping
- skip notices
- unskipping
- marking start, end times with popup
- submitting with popup
Not Working
- in-page popup

add selector for piped

---

package-lock.json
package.json
public/_locales/en/messages.json
public/content.css
public/options/options.css
public/options/options.html
src/components/CategoryPillComponent.tsx
src/config.ts
src/content.ts
src/js-components/previewBar.ts
src/utils/thumbnails.ts
src/utils/videoLabels.ts
webpack/webpack.common.js

***
The /videoLabels endpoint was added to SponsorBlockServer quite a while ago, but I didn't see any progress on the extension side, so I decided to try implementing it myself.
Labels are shown as a circle of the category's color with the sponsorblock logo in the middle (screenshot below)
When you hover over the icon, it is expanded to a rounded rectangle, with the category name shown.
The text color can be white or black, depending on the category color. (this logic was copied from regular fv labels) The logo's color will also update. (yet another screenshot below)
Category colors will update live as you change your settings. This is done using CSS …

Show Full-Video Labels on thumbnails

---

src/content.ts

***
A quick, dumb fix for a dumb issue.
It appears that dark reader sometimes forgets/fails to set it's variable overrides, which after my changes in the thumbnail-labels PR may cause SB segments on the timeline to go transparent.
This PR makes a simple change: In the CSS variable generation code, define the darkreader override variables. This ensures that if DR doesn't define them by itself, they will still be defined by SB, so segment elements will remain visible.
+whitespace trimming as an added bonus from my ide

Darkreader-proofing the dynamic CSS variables

---

src/content.ts

***
This seems to happen if incorrectVideoCheck triggers while called from skippingFunction.

Fix the incorrectVideoCheck() error showing the same videoID as recorded & actual

---

src/js-components/previewBar.ts

***
Supposed to fix segments with endtime == videoduration showing up as if they didn't actually reach the end, but the issue might be somewhere else.
Well, it still removes a `calc()` from each segment's styles

Define left + right on previewbar segments instead of left + width

---

src/components/CategoryPillComponent.tsx

***
Without this, we would try to use the color for an 'undefined' category on the first render pass of the element. It was then immediately re-rendered with a segment set, but DR missed the update, which caused it to stick to that 'undefined' category and the label became transparent.
In short, this is yet another fix/workaround for a DR bug

Reset fvlabel color definitions when segment == null

---

src/utils/pageUtils.ts

***
This should fix an issue where starting your youtube session from the home page would cause SB controls to attach to the wrong player. (unless you used :selfpromo: yt-neuter)

Don't attach controls to inline preview players

---

public/content.css

***
This fixes short segments on long videos not appearing at all in small embeds
[Issue reported on discord](https://discord.com/channels/603643120093233162/603643256714297374/1104742118519488643)

Set min width of previewbar segments to 1px

---

src/components/SponsorTimeEditComponent.tsx

***
The id for the "Preview" and "End" spans were the same. I've assigned a new ID `sponsorTimePreviewEndButton` to the "End" button.

Renamed duplicate span id

---

src/content.ts
src/popup.ts

***
The refresh animation on the popup page never ends if it is clicked on a non-video page. My fix is to send an empty message to popup, and stop the animation.
BTW: Some message handlers are using `response != undefined` to test if there is any content in the message, but a message will always have a field: `"message": "message_name"`, so the test will always pass. I found this one in `vote()` handler, maybe there are more on other pages. We should probably test if other fields exist, or exclude `message` using a util function. 
https://github.com/ajayyy/SponsorBlock/blob/742eb7ef57e1de436553eed20c45bf9542a86369/src/popup.ts#L900-L901
The printed empty message. It's not "empty"

[Fix] Stop Refresh Animation on Popup When Triggered on Non-YouTube Pages

---

src/content.ts
src/messageTypes.ts
src/popup.ts

***
This is a follow up of PR #1979. My last fix relied on the content script sending back a message to the popup. But I overlooked the case where on non-YouTube sites, the content script is not injected at all. So I switched to use the message `sendResponse` callback to inform the popup. If the refresh message receives no response, it assumes that the current page is not YouTube and stops the animation, which I think is cleaner and less convoluted.
I also refactored `infoFound` in Popup.js. It now has one less indentation and a early return.

[Fix #1979] Stop Refresh Animation on Popup When Content Script is Not Injected

---

manifest/manifest.json
src/content.ts

***
This PR fixes an issue that was reported on discord, where the after pressing the refresh button segments would sometimes show up and sometimes the segment list would be empty.
[Latest report/investigation thread in #concerns on discord](https://discord.com/channels/603643120093233162/603643256714297374/1250559680351174838)
This appears to be caused by a hidden iframe which holds the page `https://accounts.youtube.com/RotateCookiesPage`, where the content script would be injected in addition to the root page.
This iframe is only present when logged in, and as such this issue does not appear when logged out.
Both the root and iframe content scripts would …

Fix refreshing

---

webpack/webpack.common.js

***
Previously webpack compiled with 3 warnings:
Current build on this PR:

Overriding default webpack performance config to reduce warnings

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/update-oss-attribution.yml
.github/workflows/updateInvidous.yml

***
- [Node 20 is the default](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
- [Upload Artifact depricated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
For example previous warnings on PR CI:
Now:

Node deprecated versions

---

public/options/options.html
src/components/SkipNoticeComponent.tsx
src/components/options/KeybindDialogComponent.tsx
src/config.ts
src/content.ts
src/render/SkipNotice.tsx
src/types.ts
src/utils/categoryUtils.ts

***
Default keybinds are `G` and `H` respectively for Upvoting and Downvoting.
Voting affects the last or current segment.
Issue #507
Also see https://github.com/ajayyy/ExtensionTranslations/pull/76

Added keybinds for voting on segments

---

src/popup/SegmentListComponent.tsx

***
[issue reported on discord](https://discord.com/channels/603643120093233162/603643256714297374/1418563576226119722)
The issue itself was triggered by [this line in PR #2334](https://github.com/ajayyy/SponsorBlock/pull/2334/files#diff-0885c230b87020856a81ffc8cf0303ab633e364e7f79071f60e6f0a3d8c26df7R91), as it shallow-cloned the segment object. The list item component relied on object mutation propagating up to the root popup component when unhiding, which was stopped in the list display due to this clone, and even worse - the changes would be discarded on the next rerender of the list.
This PR fixes this issue by making the list item trust it's own state …

Fix segment hiding/unhiding

---

.github/workflows/release.yml
tsconfig-production.json
webpack/webpack.common.js
webpack/webpack.manifest.js
webpack/webpack.prod.js

***
This PR is a port of ajayyy/DeArrow#402, [ajayyy/DeArrow/`07764039`](https://github.com/ajayyy/DeArrow/commit/077640390bbc8eb60d85824735c463b169c182cc), ajayyy/DeArrow#407 and ajayyy/Dearrow#409 made through pure git magic.
Requires a manual pull of the [detached `source-maps` branch](https://github.com/mini-bomba/SponsorBlock/tree/source-maps) from my fork.

Port dearrow autoupdate & source maps
